import './globals.css';
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // Choose weights you need
  variable: '--font-poppins',
});


export const metadata = {
  title: "Rentcars",
  description: "Generated by create next app",
  icons: {
    icon: '/icons8-car-96.png', // located in public/favicon.ico
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.variable} >
      <head />
      <body      >
        {children}
      </body>
    </html>
  );
}
