// app/layout.js
import './globals.css';
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});

export const metadata = {
  title: "Rentcars",
  description: "Generated by create next app",
  icons: {
    icon: '/icons8-car-96.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.variable}>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons8-car-96.png" />
        <title>Rentcars</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
